apiVersion: v1
kind: ConfigMap
metadata:
  name: kubesolv-config
  namespace: {{ include "kubesolv.namespace" . }}
  labels:
    {{- include "kubesolv.labels" . | nindent 4 }}
data:
  IGNORED_NAMESPACES: {{ .Values.namespaces.ignore | join "," | quote }}
  AI_ENDPOINT: {{ .Values.ai.endpoint | quote }}
  MAX_MEMORY_LIMIT: {{ .Values.guardrails.maxMemoryLimit | quote }}
  MAX_REPLICAS: {{ .Values.guardrails.maxReplicas | quote }}
