apiVersion: v1
kind: Secret
metadata:
  name: kubesolv-secrets
  namespace: {{ include "kubesolv.namespace" . }}
  labels:
    {{- include "kubesolv.labels" . | nindent 4 }}
type: Opaque
stringData:
  LICENSE_KEY: {{ .Values.kubesolv.licenseKey | quote }}
  SLACK_BOT_TOKEN: {{ .Values.slack.botToken | quote }}
  SLACK_APP_TOKEN: {{ .Values.slack.appToken | quote }}
  SLACK_CHANNEL_ID: {{ .Values.slack.channelId | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.telegram.botToken | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.telegram.adminChatId | quote }}
  PROMETHEUS_URL: {{ .Values.prometheus.url | quote }}
